### PR TITLE
draw referenced ways and nodes for selected relations

### PR DESCRIPTION
**Pull request by tyrasd**
implements functionality for #15

Way-member drawing is implemented as a recursive call to `text2coord` which would technically even [allow](https://github.com/tyrasd/Level0/commit/9291a355965ce502a5cb322343c840e6278690ae#diff-e7e25d67ba8a15edaccd2ddd0eaba9f2R230) to draw nested relations (but I wasn't sure if that makes much sense in practice and one would have to make sure that reference-loops are handled properly, which can be hairy!).

### CODE REVIEW

**Comment by Zverik** [comment]
Okay, this looks good, though I'm not sure this is useful. Thanks.

**Comment by tyrasd** [comment]
> I'm not sure this is useful.

Why not?

**Comment by Zverik** [comment]
Relations are usually obvious from their tags (e.g. routes), and if not, showing their members would be more useful, since the focus of this editor is on individual objects.

**Comment by tyrasd** [comment]
So, why had you proposed https://github.com/Zverik/Level0/issues/15#issue-34696140, then? :confused:

**Comment by Zverik** [comment]
I proposed to draw single referenced members of relations.

**Comment by tyrasd** [comment]
Aaah, I see. That would make sense as well. For example, the selected member could be drawn in a separate "highlight" colour. I'll see what I can do…

**Pull request merged**
